### ISSUE TITLE
docker compose fails on windows

### ISSUE THREAD

**Issue by rosiecakes** [docker/example-voting-app#29] opened 2016-07-29 18:24 UTC
Ran docker-machine upgrade and then docker-compose up from within this repo dir, it stalls after connection to redis:

``````
$ docker-compose up
Starting examplevotingappmaster_vote_1
Starting examplevotingappmaster_result_1
Starting examplevotingappmaster_db_1
Starting examplevotingappmaster_worker_1
Starting examplevotingappmaster_redis_1

ERROR: for vote  mkdir /c/Users/xcs2188-ta/My Documents: file exists

ERROR: for result  mkdir /c/Users/xcs2188-ta/My Documents: file exists
Attaching to examplevotingappmaster_redis_1, examplevotingappmaster_worker_1, examplevotingappmaster_db_1
←[36mredis_1   |←[0m                 _._
←[36mredis_1   |←[0m            _.-``__ ''-._
←[36mredis_1   |←[0m       _.-``    `.  `_.  ''-._           Redis 3.2.1 (00000000/0) 64 bit
←[36mredis_1   |←[0m   .-`` .-```.  ```\/    _.,_ ''-._
←[36mredis_1   |←[0m  (    '      ,       .-`  | `,    )     Running in standalone mode
←[36mredis_1   |←[0m  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
←[36mredis_1   |←[0m  |    `-._   `._    /     _.-'    |     PID: 1
←[36mredis_1   |←[0m   `-._    `-._  `-./  _.-'    _.-'
←[36mredis_1   |←[0m  |`-._`-._    `-.__.-'    _.-'_.-'|
←[36mredis_1   |←[0m  |    `-._`-._        _.-'_.-'    |           http://redis.io
←[36mredis_1   |←[0m   `-._    `-._`-.__.-'_.-'    _.-'
←[36mredis_1   |←[0m  |`-._`-._    `-.__.-'    _.-'_.-'|
←[36mredis_1   |←[0m  |    `-._`-._        _.-'_.-'    |
←[36mredis_1   |←[0m   `-._    `-._`-.__.-'_.-'    _.-'
←[36mredis_1   |←[0m       `-._    `-.__.-'    _.-'
←[36mredis_1   |←[0m           `-._        _.-'
←[36mredis_1   |←[0m               `-.__.-'
←[36mredis_1   |←[0m
←[36mredis_1   |←[0m 1:M 29 Jul 18:19:52.438 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/
sys/net/core/somaxconn is set to the lower value of 128.
←[36mredis_1   |←[0m 1:M 29 Jul 18:19:52.439 # Server started, Redis version 3.2.1
←[36mredis_1   |←[0m 1:M 29 Jul 18:19:52.439 # WARNING overcommit_memory is set to 0! Background save may fail under low
 memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the comma
nd 'sysctl vm.overcommit_memory=1' for this to take effect.
←[36mredis_1   |←[0m 1:M 29 Jul 18:19:52.439 # WARNING you have Transparent Huge Pages (THP) support enabled in your ker
nel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/k
ernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a
reboot. Redis must be restarted after THP is disabled.
←[36mredis_1   |←[0m 1:M 29 Jul 18:19:52.439 * The server is now ready to accept connections on port 6379
←[32mdb_1      |←[0m LOG:  database system was shut down at 2016-07-29 18:17:50 UTC
←[32mdb_1      |←[0m LOG:  MultiXact member wraparound protections are now enabled
←[32mdb_1      |←[0m LOG:  database system is ready to accept connections
←[32mdb_1      |←[0m LOG:  autovacuum launcher started
←[33mworker_1  |←[0m Connected to db
←[33mworker_1  |←[0m Found redis at 172.18.0.2
←[33mworker_1  |←[0m Connected to redis
``````

**Comment by ManoMarks** [comment] 2016-10-31 20:51
@rosiecakes I can't reproduce this. Have you tried recently?

**Comment by rosiecakes** [comment] 2016-10-31 20:55
Nope, I just gave up.

**Comment by ManoMarks** [comment] 2016-10-31 20:57
Were you using Docker for Windows or Docker Toolbox? I'm going to close this for now because Docker for Windows is substantially updated since, but please reopen if you encounter the issue again.

**Closed by ManoMarks** 2016-10-31 20:57 UTC
